--- #YAML:1.0
name:               Text-FixedWidth
version:            0.07
abstract:           Easy OO manipulation of fixed width text files
author:
    - Jay Hannah <jay@jays.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    Test::Warn:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
