# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-FixedWidth
version:      0.04
version_from: lib/Text/FixedWidth.pm
installdirs:  site
requires:
    Test::More:                    0
    Test::Warn:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
