--- #YAML:1.0
name:                Text-FixedWidth
version:             0.02
abstract:            Easy OO manipulation of fixed width text files.
license:             ~
author:              
    - Jay Hannah <jay@jays.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    Test::Warn:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
